/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_a3;

import Models.Employee;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author netoe
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        ImagemAbertura = new javax.swing.JLabel();
        TextoLoginAbertura = new javax.swing.JLabel();
        CaixadeEmail = new javax.swing.JTextField();
        CaixaSenha = new javax.swing.JTextField();
        CheckLembrarSenha = new javax.swing.JCheckBox();
        BotaoEsqueceuSenha = new javax.swing.JButton();
        BotaoSignIn = new javax.swing.JButton();
        TextoNovo = new javax.swing.JLabel();
        TextoCreateAccount = new javax.swing.JLabel();
        IconeUsername = new javax.swing.JLabel();
        IconePassword = new javax.swing.JLabel();
        ImagemCadastro = new javax.swing.JLabel();
        TituloRegistro = new javax.swing.JLabel();
        CaixaEmail = new javax.swing.JTextField();
        CaixaPhoneNumber = new javax.swing.JTextField();
        CaixaPassword = new javax.swing.JTextField();
        CaixaFirstName = new javax.swing.JTextField();
        CaixaLastName = new javax.swing.JTextField();
        BotaoRegister = new javax.swing.JButton();
        BotaoCancel = new javax.swing.JToggleButton();
        CheckBoxNewsletter = new javax.swing.JCheckBox();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Sign In");
        jFrame1.setBackground(new java.awt.Color(255, 255, 255));

        ImagemAbertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_a3/imagens/Background.png"))); // NOI18N
        ImagemAbertura.setText("jLabel1");
        ImagemAbertura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TextoLoginAbertura.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        TextoLoginAbertura.setForeground(new java.awt.Color(0, 0, 0));
        TextoLoginAbertura.setText("Sign In");

        CaixadeEmail.setText("Username or email");
        CaixadeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixadeEmailActionPerformed(evt);
            }
        });

        CaixaSenha.setText("Password");

        CheckLembrarSenha.setText("Remember-me");

        BotaoEsqueceuSenha.setText("Forgot Password?");
        BotaoEsqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEsqueceuSenhaActionPerformed(evt);
            }
        });

        BotaoSignIn.setText("Sign In");

        TextoNovo.setText("New here?");

        TextoCreateAccount.setForeground(new java.awt.Color(51, 51, 255));
        TextoCreateAccount.setText("Create an Account");

        IconeUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_a3/imagens/login.png"))); // NOI18N

        IconePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_a3/imagens/senha.png"))); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(ImagemAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addComponent(TextoNovo)
                                .addGap(30, 30, 30)
                                .addComponent(TextoCreateAccount)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IconeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addComponent(IconePassword)
                                        .addGap(2, 2, 2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addComponent(CheckLembrarSenha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(BotaoEsqueceuSenha))
                                    .addComponent(CaixadeEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CaixaSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotaoSignIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(51, 51, 51))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(TextoLoginAbertura)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(TextoLoginAbertura)
                        .addGap(32, 32, 32)
                        .addComponent(CaixadeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IconeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CaixaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(IconePassword)))
                .addGap(35, 35, 35)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckLembrarSenha)
                    .addComponent(BotaoEsqueceuSenha))
                .addGap(37, 37, 37)
                .addComponent(BotaoSignIn)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNovo)
                    .addComponent(TextoCreateAccount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(560, 280));
        setMinimumSize(new java.awt.Dimension(793, 514));
        setResizable(false);
        setSize(new java.awt.Dimension(793, 542));

        ImagemCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_a3/imagens/sTOCK.png"))); // NOI18N
        ImagemCadastro.setText("jLabel1");
        ImagemCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TituloRegistro.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        TituloRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TituloRegistro.setText(" Register");

        CaixaEmail.setText("Email");
        CaixaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaEmailActionPerformed(evt);
            }
        });

        CaixaPhoneNumber.setText("Phone Number");
        CaixaPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaPhoneNumberActionPerformed(evt);
            }
        });

        CaixaPassword.setText("Password");

        CaixaFirstName.setText("First Name");

        CaixaLastName.setText("Last Name");

        BotaoRegister.setText("Register");
        BotaoRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoRegisterMouseClicked(evt);
            }
        });
        BotaoRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegisterActionPerformed(evt);
            }
        });

        BotaoCancel.setText("Cancel");
        BotaoCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoCancelMouseClicked(evt);
            }
        });
        BotaoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelActionPerformed(evt);
            }
        });

        CheckBoxNewsletter.setText("Subscribe Newsletter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ImagemCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TituloRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CaixaLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CaixaEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CaixaPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CaixaPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CaixaFirstName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckBoxNewsletter)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(BotaoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(TituloRegistro)
                .addGap(34, 34, 34)
                .addComponent(CaixaFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CaixaLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CaixaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CaixaPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CaixaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckBoxNewsletter)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRegister)
                    .addComponent(BotaoCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaixadeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixadeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixadeEmailActionPerformed

    private void BotaoEsqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEsqueceuSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEsqueceuSenhaActionPerformed

    private void CaixaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaEmailActionPerformed

    private void CaixaPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaPhoneNumberActionPerformed

    private void BotaoRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoRegisterMouseClicked
        try {
            Employee employee = new Employee(this.CaixaFirstName.getText(),
                    this.CaixaLastName.getText(), this.CaixaEmail.getText(),
                    this.CaixaPhoneNumber.getText(), this.CaixaPassword.getText());
            employee.Register();
            System.out.println("Employee registred.");
            ConfirmarRegistro NovaTela = new ConfirmarRegistro ();
            NovaTela.setVisible(true);
            TelaCadastro FecharTela = new TelaCadastro(); 
            FecharTela.setVisible(false); dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BotaoRegisterMouseClicked

    private void BotaoRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRegisterActionPerformed

    private void BotaoCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCancelActionPerformed

    private void BotaoCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCancelMouseClicked
        TelaCadastro FecharTela = new TelaCadastro(); 
        FecharTela.setVisible(false); dispose();
        
        TelaAbertura NovaTela = new TelaAbertura(); 
        NovaTela.setVisible(true);
        
        
    }//GEN-LAST:event_BotaoCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoCancel;
    private javax.swing.JButton BotaoEsqueceuSenha;
    private javax.swing.JButton BotaoRegister;
    private javax.swing.JButton BotaoSignIn;
    private javax.swing.JTextField CaixaEmail;
    private javax.swing.JTextField CaixaFirstName;
    private javax.swing.JTextField CaixaLastName;
    private javax.swing.JTextField CaixaPassword;
    private javax.swing.JTextField CaixaPhoneNumber;
    private javax.swing.JTextField CaixaSenha;
    private javax.swing.JTextField CaixadeEmail;
    private javax.swing.JCheckBox CheckBoxNewsletter;
    private javax.swing.JCheckBox CheckLembrarSenha;
    private javax.swing.JLabel IconePassword;
    private javax.swing.JLabel IconeUsername;
    private javax.swing.JLabel ImagemAbertura;
    private javax.swing.JLabel ImagemCadastro;
    private javax.swing.JLabel TextoCreateAccount;
    private javax.swing.JLabel TextoLoginAbertura;
    private javax.swing.JLabel TextoNovo;
    private javax.swing.JLabel TituloRegistro;
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables
}
