/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_a3;

import Models.Vehicle;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author netoe
 */
public class TelaCadastroVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroVeiculos
     */
    public TelaCadastroVeiculos() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        Separador = new javax.swing.JSeparator();
        TextoTopo = new javax.swing.JLabel();
        TextoModelVehicle = new javax.swing.JLabel();
        TextoBrand = new javax.swing.JLabel();
        TextoPlateVehicle = new javax.swing.JLabel();
        CaixaPlateVehicle = new javax.swing.JTextField();
        TextoYear = new javax.swing.JLabel();
        TextoChassi = new javax.swing.JLabel();
        CaixaChassi = new javax.swing.JTextField();
        TextoColor = new javax.swing.JLabel();
        BotaoRegister = new javax.swing.JButton();
        TextoDescription = new javax.swing.JLabel();
        CaixaDescription = new javax.swing.JTextField();
        BotaoCancel = new javax.swing.JButton();
        CaixaModelVehicle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaVeiculos = new javax.swing.JTable();
        TextoPrice = new javax.swing.JLabel();
        CaixaPrice = new javax.swing.JTextField();
        ImagemTopo = new javax.swing.JLabel();
        CaixaBrand = new javax.swing.JTextField();
        CaixaYear = new javax.swing.JTextField();
        CaixaColor = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Vehicle");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.blue);
        setLocation(new java.awt.Point(560, 300));
        setMinimumSize(new java.awt.Dimension(799, 328));
        setResizable(false);
        setSize(new java.awt.Dimension(799, 328));

        Separador.setBackground(new java.awt.Color(0, 0, 0));
        Separador.setForeground(new java.awt.Color(0, 0, 0));

        TextoTopo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextoTopo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoTopo.setText(" Enter all the information requested to register the vehicle");

        TextoModelVehicle.setBackground(new java.awt.Color(255, 255, 255));
        TextoModelVehicle.setText("Model Vehicle:");

        TextoBrand.setText("Brand:");

        TextoPlateVehicle.setText("Plate Vehicle:");

        TextoYear.setText("Year:");

        TextoChassi.setText("Chassi:");

        TextoColor.setText("Color:");

        BotaoRegister.setText("Register");
        BotaoRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoRegisterMouseClicked(evt);
            }
        });
        BotaoRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegisterActionPerformed(evt);
            }
        });

        TextoDescription.setText("Description:");

        BotaoCancel.setText("Cancel");
        BotaoCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoCancelMouseClicked(evt);
            }
        });

        TabelaVeiculos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model ", "Plate", "Chassi", "Brand", "Year", "Color", "Descriptions", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaVeiculos.setDragEnabled(true);
        TabelaVeiculos.setName(""); // NOI18N
        TabelaVeiculos.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(TabelaVeiculos);

        TextoPrice.setText("Price:");

        ImagemTopo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_a3/imagens/Inicial.png"))); // NOI18N

        CaixaBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaBrandActionPerformed(evt);
            }
        });

        CaixaYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Separador)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TextoDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextoModelVehicle)
                                        .addComponent(TextoPlateVehicle))
                                    .addComponent(TextoChassi, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CaixaPlateVehicle)
                                .addComponent(CaixaChassi, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(CaixaModelVehicle))
                            .addComponent(CaixaDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoYear)
                            .addComponent(TextoColor)
                            .addComponent(TextoPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CaixaYear)
                            .addComponent(CaixaColor)
                            .addComponent(CaixaPrice)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CaixaBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(ImagemTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ImagemTopo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoTopo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoModelVehicle)
                    .addComponent(TextoBrand)
                    .addComponent(CaixaModelVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaixaBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoPlateVehicle)
                    .addComponent(CaixaPlateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoYear)
                    .addComponent(CaixaYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaixaChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoColor)
                    .addComponent(TextoChassi)
                    .addComponent(CaixaColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaixaDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoDescription)
                    .addComponent(TextoPrice)
                    .addComponent(CaixaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRegister)
                    .addComponent(BotaoCancel))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCancelMouseClicked
        TelaCadastroVeiculos FecharTela = new TelaCadastroVeiculos();
        FecharTela.setVisible(false); dispose();
    }//GEN-LAST:event_BotaoCancelMouseClicked

    private void BotaoRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoRegisterMouseClicked

    }//GEN-LAST:event_BotaoRegisterMouseClicked

    private void BotaoRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegisterActionPerformed
        try {
            Vehicle vehicle = new Vehicle(this.CaixaPlateVehicle.getText(),
                    this.CaixaChassi.getText(), this.CaixaModelVehicle.getText(),
                    this.CaixaBrand.getText(), parseInt(this.CaixaYear.getText()), 
                    this.CaixaColor.getText(), this.CaixaDescription.getText(),
                    parseDouble(this.CaixaPrice.getText()));
            vehicle.Register();
            System.out.println("Vehicle registred.");
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel Tabela = (DefaultTableModel) this.TabelaVeiculos.getModel();
        Tabela.addRow(new Object[] {this.CaixaModelVehicle.getText(), this.CaixaPlateVehicle.getText(), this.CaixaChassi.getText(), this.CaixaBrand.getText(), this.CaixaYear.getText(), this.CaixaColor.getText(), this.CaixaDescription.getText(), this.CaixaPrice.getText()});

    }//GEN-LAST:event_BotaoRegisterActionPerformed

    private void CaixaBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaBrandActionPerformed

    private void CaixaYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancel;
    private javax.swing.JButton BotaoRegister;
    private javax.swing.JTextField CaixaBrand;
    private javax.swing.JTextField CaixaChassi;
    private javax.swing.JTextField CaixaColor;
    private javax.swing.JTextField CaixaDescription;
    private javax.swing.JTextField CaixaModelVehicle;
    private javax.swing.JTextField CaixaPlateVehicle;
    private javax.swing.JTextField CaixaPrice;
    private javax.swing.JTextField CaixaYear;
    private javax.swing.JLabel ImagemTopo;
    private javax.swing.JSeparator Separador;
    private javax.swing.JTable TabelaVeiculos;
    private javax.swing.JLabel TextoBrand;
    private javax.swing.JLabel TextoChassi;
    private javax.swing.JLabel TextoColor;
    private javax.swing.JLabel TextoDescription;
    private javax.swing.JLabel TextoModelVehicle;
    private javax.swing.JLabel TextoPlateVehicle;
    private javax.swing.JLabel TextoPrice;
    private javax.swing.JLabel TextoTopo;
    private javax.swing.JLabel TextoYear;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
